### ISSUE TITLE
[FEAT REQUEST] Please make PicaComicAPI._fetch method public

### ISSUE THREAD

**Issue by dragon-fish** [l2studio/picacomic-api#2]
RT

Make it possible to build custom requests.

Thank you:pray:!

**Comment by dragon-fish** [comment]
Although it can be used currently. But it looks awkward. 🤣

![](https://user-images.githubusercontent.com/44761872/135903903-0b9f07d4-ca37-4c08-a000-4c44e5bdf5b8.png)

**Comment by lgou2w** [comment]
This is an oversight of the design, it will be fixed soon. :rofl:

**Comment by lgou2w** [comment]
Resolved in [`0.1.7`](https://github.com/l2studio/picacomic-api/releases/tag/0.1.7) version.
